In [1]:
import os
import numpy as np
import pandas as pd
import json
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stat
import pingouin as pg

In [2]:
os.chdir('exp1_rep_debug_data')

In [6]:
os.listdir()

['exp1_rep_test.txt']

In [8]:
for id in os.listdir():
    data = json.load(open(id))           # one participant
    experiment_df  = pd.DataFrame(data["trials"])
    sound_check_df = pd.DataFrame(data["soundCheck"])
    demographic_df = pd.DataFrame([data["demographics"]])

In [8]:
demographic_df

,gender,hispanic,race,age,location,strategy,feedback,subject_id,study_id,session_id,...,debug,nBlocks,windowWidth,windowHeight,screenWidth,screenHeight,refreshRate,hc_passed,hc_totalCorrect,hc_numTrials
0,Female,No,Asian,24,,,,test03,None,None,...,1,1,1536,826,1536,960,61.55068,True,5,6

In [9]:
sound_check_df

,pair,first_condition,second_condition,softer_position,response_position,correct,n_replays,rt
0,lower_vs_higher,higher,lower,2,2,1,1,8631
1,same_vs_lower,same,lower,2,2,1,0,3467
2,same_vs_higher,same,higher,1,1,1,0,3293

In [7]:
experiment_df

,id,trial_number,trialID,soundCondition,chargeSpeed,leftColor,ISI_ms,repetition,response,is_fight,response_rt,confidence,confidence_rt,subject_id
0,test03,1,0890b767-b394-4f89-aea1-c60cab7014af,lower,4.0,grey,526.2,9,play,0,1120,82.000000,3736,test03
1,test03,2,68382d9c-6cc5-4669-84bf-c8058e3c1472,higher,4.0,black,490.5,1,play,0,1603,63.200002,2155,test03
2,test03,3,e838dadb-c02f-4273-ae93-210720dcd06c,same,1.5,grey,475.9,9,fight,1,784,32.266673,1638,test03